# Generated by Django 4.0.4 on 2022-06-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='is_lending',
            field=models.BooleanField(default=True, help_text='貸し出し中ならTrue'),
        ),
    ]
