# Generated by Django 5.0.7 on 2024-07-16 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='is_lending',
            field=models.BooleanField(default=True, help_text='貸し出し中ならTrue ※返却時は管理者に問合わせください'),
        ),
    ]
